name: CI

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up py
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint
      working-directory: ./
      run: |
        black --check ./
        flake8
        python -m pytest
